### ISSUE TITLE
pcangsd.py -h fails with numba error

### ISSUE THREAD

**Issue by samfux84** [Rosemeis/pcangsd#3]
Hi,

I got the following error when trying to run pcangsd after installation:

```
[sfux@eu-login-07 ~]$ module load gcc/4.8.2 gdc python/2.7.11 pcangsd/0.8.0    
Autoloading openblas/0.2.13_seq
[sfux@eu-login-07 ~]$ pcangsd.py -h
Traceback (most recent call last):
  File "/cluster/apps/gdc/pcangsd/0.8.0/pcangsd.py", line 12, in <module>
    from covariance import *
  File "/cluster/apps/gdc/pcangsd/0.8.0/covariance.py", line 19, in <module>
    @jit("void(f4[:, :], f4[:], i8, i8, f4[:, :])", nopython=True, nogil=True, cache=True)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/decorators.py", line 172, in wrapper
    disp.compile(sig)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/dispatcher.py", line 350, in compile
    flags=flags, locals=self.locals)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/compiler.py", line 644, in compile_extra
    return pipeline.compile_extra(func)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/compiler.py", line 361, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/compiler.py", line 370, in compile_bytecode
    return self._compile_bytecode()
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/compiler.py", line 631, in _compile_bytecode
    return pm.run(self.status)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/compiler.py", line 251, in run
    raise patched_exception
numba.errors.TypingError: Caused By:
Traceback (most recent call last):
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/compiler.py", line 243, in run
    res = stage()
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/compiler.py", line 458, in stage_nopython_frontend
    self.locals)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/compiler.py", line 759, in type_inference_stage
    infer.propagate()
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typeinfer.py", line 510, in propagate
    raise errors[0]
TypingError: Internal error at <numba.typeinfer.CallConstraint object at 0x2afffaa14890>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typeinfer.py", line 111, in propagate
    constraint(typeinfer)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typeinfer.py", line 270, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typeinfer.py", line 297, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typing/context.py", line 113, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/types.py", line 222, in get_call_type
    return self.template(context).apply(args, kws)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typing/templates.py", line 155, in apply
    sig = generic(args, kws)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typing/npydecl.py", line 344, in generic
    assert not kws
AssertionError
--%<-----------------------------------------------------------------

File "../../apps/gdc/pcangsd/0.8.0/covariance.py", line 31

Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x2afffaa14890>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typeinfer.py", line 111, in propagate
    constraint(typeinfer)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typeinfer.py", line 270, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typeinfer.py", line 297, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typing/context.py", line 113, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/types.py", line 222, in get_call_type
    return self.template(context).apply(args, kws)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typing/templates.py", line 155, in apply
    sig = generic(args, kws)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/numba/typing/npydecl.py", line 344, in generic
    assert not kws
AssertionError
--%<-----------------------------------------------------------------

File "../../apps/gdc/pcangsd/0.8.0/covariance.py", line 31
[sfux@eu-login-07 ~]$ 
```

any idea ?

I am using numba 0.22.1 and llvmlite 0.8.0 which uses LLVM 3.6.0.

**Comment by Rosemeis** [comment]
Hi,
I can't reproduce the problem with numba 0.35.0 and llvmlite 0.20.0 on our server. So the problem might be rooted in some used functionality not supported by earlier versions of numba/llvmlite in our code. That's the best I got, sorry!

**Comment by samfux84** [comment]
@Rosemeis: Thank you for your feedback.

I upgraded to llvmlite 0.20.0 and numba 0.35.0 and now everything works.
