### ISSUE TITLE
gzip: stdout: Broken pipe

### ISSUE THREAD

**Issue by DrLaurenCWhite** [Rosemeis/pcangsd#36]
Hello,
I am getting the following error when I try to run PCAngsd. I've successfully run the program before on a different beagle file, but the last few I have tried throw this same error:

"
Using 1 thread(s)

Parsing Beagle file

gzip: stdout: Broken pipe
Traceback (most recent call last):
  File "/usr/local64/opt/pcangsd/pcangsd.py", line 124, in <module>
    likeMatrix = readGzipBeagle(args.beagle)
  File "/usr/local64/opt/pcangsd/helpFunctions.py", line 22, in readGzipBeagle
    likeMatrix = np.empty((m3, 15000000), dtype=np.float32)
MemoryError
"

The command I am using is:
python /usr/local64/opt/pcangsd/pcangsd.py -beagle ./All_minInd50_md3_chr1.beagle.gz -o ../PCA_Admixture/All_minInd50_md3_chr1

Any help would be really appreciated.
Thanks
-Lauren

**Comment by DrLaurenCWhite** [comment]
never mind. I updated to the latest version and the issue is resolved. :)
