### ISSUE TITLE
Cynthonization behaving strangely

### ISSUE THREAD

**Issue by gLaRob** [Rosemeis/pcangsd#62]
Hello,

I followed the solution suggested in #61 but it did not work for me. I had a previous version of Angsd running but some dependencies were uninstalled so I attempted to reinstall Angsd and had this happen.

```
Traceback (most recent call last):
  File "pcangsd/pcangsd/pcangsd.py", line 455, in <module>
    main()
  File "/pcangsd/pcangsd/pcangsd.py", line 148, in main
    from pcangsd import reader_cy
ImportError: cannot import name 'reader_cy' from 'pcangsd' (pcangsd/pcangsd/pcangsd.py)
```

One thing I did notice was the following during my initial install. I am not entirely sure how to resolve this.
`Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]`

Many thanks

**Comment by Rosemeis** [comment]
Hi,

Can you try and remove the folder pcangsd folder completely and reinstall completely and run following command?
`git clone https://github.com/Rosemeis/pcangsd.git; cd pcangsd; python setup.py build_ext --inplace; pip3 install -e .`

Make sure the dependencies are installed (numpy, scipy, cython).

Best,
Jonas

**Comment by gLaRob** [comment]
Hello,

Thanks for your swift response.
Here are the commands I used to install and the output I received.

Removed old pcangsd folder
`rm -r pcangsd/
`
clone pcangsd
`git clone https://github.com/Rosemeis/pcangsd.git
`
check requirements

`pip install --user -r requirements.txt`

`
Requirement already satisfied: numpy in lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.22.4)
Requirement already satisfied: scipy lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.8.1)
Requirement already satisfied: cython in lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.29.30)
`

'build_ext --inplace'

'pip3 install -e .'
'Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///bigdata/brelsfordlab/glagu001/pcangsd
Requirement already satisfied: numpy in lib/python3.9/site-packages (from PCAngsd==1.10) (1.22.4)
Requirement already satisfied: cython in lib/python3.9/site-packages (from PCAngsd==1.10) (0.29.30)
Requirement already satisfied: scipy in lib/python3.9/site-packages (from PCAngsd==1.10) (1.8.1)
Installing collected packages: PCAngsd
  Running setup.py develop for PCAngsd
Successfully installed PCAngsd-1.10'

I receive the same error. The only thing I have noticed that may be off are the following


when attempting to run
'
ImportError: cannot import name 'reader_cy' from 'pcangsd'
'

and
when installing pcangsd
'
#warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
'
Is my Numpy the issue even though the requirement appears to be met?

**Comment by Rosemeis** [comment]
The warning of the NumPy API should not be a problem. Just to make sure, what is your command when calling pcangsd? I changed it to a command-line like program, so old tutorials might not capture that.

Example:
`pcangsd -b input.beagle.gz -e 2 -t 64 -o output.pcangsd`

**Comment by gLaRob** [comment]
The issue was the library paths and python paths on my end. Thank you for the help!

**Comment by gLaRob** [comment]
Apologies for reopening this issue. Here is what I was forwarded today by
the people that manage our computer cluster.
"Those files" is referring to our temporary fix and the pcangsd script that
came with the install.

"When I checked into this there seemed to be an issue with the install, or
the software itself.

It may be best to communicate with the authors, as you have already started.

The only difference between those files is a single import at line 16:

> from pcangsd import reader_cy

When testing this file with the exports it worked.
However there were still some issues importing later in the file.
Which seems odd."
