### ISSUE TITLE
ImportError: cannot import name 'reader_cy' from pcangsd

### ISSUE THREAD

**Issue by ashno376** [Rosemeis/pcangsd#69]
Hi

I am having an issue running PCangsd on a HPC linux environment. I am getting the error:

 Traceback (most recent call last):
  File "/mnt/scratch/nodelete/c1769413/bin/conda/bin/pcangsd/pcangsd/pcangsd.py", line 476, in <module>
    main()
  File "/mnt/scratch/nodelete/c1769413/bin/conda/bin/pcangsd/pcangsd/pcangsd.py", line 148, in main
    from pcangsd import shared
ImportError: cannot import name 'shared' from 'pcangsd' (/mnt/scratch/nodelete/c1769413/bin/conda/bin/pcangsd/pcangs/pcangsd.py)

I have tried:

removing and reinstalling pcangsd according to the following steps:

1.  conda install -c conda-forge c-compiler
2.  conda install -c conda-forge cxx-compiler
3.  git clone https://github.com/Rosemeis/pcangsd.git
4.  cd pcangsd/
5.  python setup.py build_ext --inplace
6.  pip install --user -r requirements.txt
7.  pip3 install -e .

adding the pcangsd folder to both my PATH and PYTHONPATH 

I can see others have had this issue, but the previous steps seemed to have solved the issue for them, and haven't worked for me unfortunately. Any help would be greatly appreciated!

**Comment by ashno376** [comment]
This issue has been solved: because I was operating on a shared high power computing cluster, I was using the default python, but did not have permissions to install modules, which I think was causing the error. When creating a python virtual environment, and uninstalling and reinstalling as above, the program ran as intended.
