### ISSUE TITLE
cannot import name 'reader_cy' from 'pcangsd' 

### ISSUE THREAD

**Issue by cnxiaobo94** [Rosemeis/pcangsd#71]
Hi! Rosemeis,
         The installation was done as your inst., but a problem occurred as below. Could you please do me a favor?
--------------------------------------------------
Traceback (most recent call last):
  File "/home/xiaobo/bioinformatics/xiaobo_analyses/../pcangsd/pcangsd/pcangsd.py", line 476, in <module>
    main()
  File "/home/xiaobo/bioinformatics/xiaobo_analyses/../pcangsd/pcangsd/pcangsd.py", line 147, in main
    from pcangsd import reader_cy
ImportError: cannot import name 'reader_cy' from 'pcangsd' (/home/xiaobo/bioinformatics/pcangsd/pcangsd/pcangsd.py)

**Comment by Rosemeis** [comment]
Hi,

Can you send me the command that you have used. :-)
It could be if you work in a HPC environment that it doesn't use your correct python, see #69 

Best,
Jonas

**Comment by cnxiaobo94** [comment]
> 
### python3 ../pcangsd/pcangsd/pcangsd.py --beagle moosePCA.beagle.gz --out moosePCA --threads 8

I used the above command and met a problem like before. After I set an environment path to 'path/to/pcangsd', I used the below command and it worked.

### pcangsd --beagle moosePCA.beagle.gz --out moosePCA --threads 8

**Comment by aguilar-gomez** [comment]
You solved my problem, I was running previous versions of pcangsd with python3 before and this one you have to run direclty
