### ISSUE TITLE
zcat: can't stat 

### ISSUE THREAD

**Issue by EwersAquaGenomics** [Rosemeis/pcangsd#85]
Dear Rosemeis, 
I installed pcangsd as described on your github page onto my Mac (os Ventura). I generated a beagle file like so in angsd: 
% angsd -GL 2 -out input -nThreads 4 -doGlf 2 -doMajorMinor 1 -doMaf 2 -SNP_pval 1e-6 -bam GER-BE-Asia.bamlist

But when I ran pcangsd as shown below, I got an error message... Some googling suggests this may be a mac issue. Do you have any ideas how I could solve this?

Thank you!
Christine

% pcangsd -b input.beagle.gz -o output/trial
-------------------------------------
PCAngsd v1.21
Jonas Meisner and Anders Albrechtsen.
Using 20 thread(s).
-------------------------------------

Parsing Beagle file.
zcat: can't stat: input.beagle.gz (input.beagle.gz.Z): No such file or directory
Traceback (most recent call last):
  File "/Users/ewers.christine/opt/anaconda3/bin/pcangsd", line 8, in <module>
    sys.exit(main())
  File "/Users/ewers.christine/opt/anaconda3/lib/python3.8/site-packages/pcangsd/pcangsd.py", line 158, in main
    L = reader_cy.readBeagle(args.beagle)
  File "pcangsd/reader_cy.pyx", line 14, in pcangsd.reader_cy.readBeagle
  File "pcangsd/reader_cy.pyx", line 52, in pcangsd.reader_cy.readBeagle
ValueError: negative dimensions are not allowed

**Comment by EwersAquaGenomics** [comment]
I found a solution to my problem. I added ".Z" to the end of my beagle file and specified this file (with the .Z ending) in the pcangsd command like so:

% pcangsd -b input.beagle.gz.Z -o output/trial
