### ISSUE TITLE
ZeroDivisionError: float division by zero, new "old" error

### ISSUE THREAD

**Issue by cbossu** [Rosemeis/pcangsd#87]
Hello,
I know there was an older post related to this (it's currently closed), but this has only recently become an issue for us. My collaborators are getting the following error when running the newer version of pcangd (v1.21). We have converted an imputed vcf file (no missing data) to a bed file in plink, and we are running pcangsd --admix across multiple values of -e. The error, attached below, shows pcangsd is reading the plink file.

Parsing PLINK files.
Loaded 1872314 sites and 121 individuals.
Estimating minor allele frequencies.
Traceback (most recent call last):
File "/usr/local/Dist/anaconda-WGSassign/envs/WGSassign/bin/pcangsd", line 8, in
sys.exit(main())
File "/usr/local/Dist/anaconda-WGSassign/envs/WGSassign/lib/python3.10/site-packages/pcangsd/pcangsd.py", line 219, in main
f = shared.emMAF(L, args.maf_iter, args.maf_tole, args.threads)
File "/usr/local/Dist/anaconda-WGSassign/envs/WGSassign/lib/python3.10/site-packages/pcangsd/shared.py", line 50, in emMAF
alpha = -max(1.0, sqrt(sr2/sv2))
**ZeroDivisionError: float division by zero**

Note that I do not get this error when I run --admix on an earlier pcangsd version (1.11). We are using the same data set. Any ideas on why this would be happening with the newer version of pcangsd?

Thanks,

Christen

**Comment by Rosemeis** [comment]
Hi,

Sorry for the late reply. The issue arises after I added some speed-up, which assumes there are some missingness present. But I have just pushed an update here on GitHub. Let me know if it helped! :-) 

Best,
Jonas

**Comment by jsoghigian** [comment]
Hi Jonas - investigating this error and it looks like that this is my issue, too! The fix you refer to, should it be in v1.36.1?

**Comment by Rosemeis** [comment]
Yes, I changed the acceleration schemes in all EM algorithms. Are you still having issues with v1.36.1? :-)

Best,
Jonas

________________________________

**Comment by jsoghigian** [comment]
I am! I've tried with imputed data, where I get this error:
```
$ pcangsd --plink subsample2.imputed --threads 12 --out selection_pcangsd --selection
------------------------------------
PCAngsd v1.36.1
Jonas Meisner and Anders Albrechtsen
Using 12 thread(s)
------------------------------------

Parsing PLINK files.
Loaded 829711 sites and 30 samples.
Estimating minor allele frequencies.
EM (MAF) failed to converge!
Number of sites after MAF filtering (0.05): 0

Estimating covariance matrix.
Traceback (most recent call last):
  File "/path/to/pcangsd/bin/pcangsd", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/path/to/pcangsd/lib/python3.13/site-packages/pcangsd/main.py", line 300, in main
    C, P, K, it, converged = covariance.emPCA(L, f, args.eig, args.iter, args.tole)
                             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/pcangsd/lib/python3.13/site-packages/pcangsd/covariance.py", line 38, in emPCA
    C *= 1.0/float(M)
         ~~~^~~~~~~~~
ZeroDivisionError: float division by zero
```

**Comment by Rosemeis** [comment]
Alright, thank you for reporting!

If you can compare and run PLINK with "--maf 0.05", how many SNPs are left after the MAF filtering step?

________________________________

**Comment by jsoghigian** [comment]
Looks like 825K...

```
$ plink --bfile subsample2.imputed --maf 0.05 --make-bed --no-sex --allow-extra-chr --out subsample_maf
PLINK v1.90b6.26 64-bit (2 Apr 2022)           www.cog-genomics.org/plink/1.9/
(C) 2005-2022 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to subsample_maf.log.
Options in effect:
  --allow-extra-chr
  --bfile subsample2.imputed
  --maf 0.05
  --make-bed
  --no-sex
  --out subsample_maf

257380 MB RAM detected; reserving 128690 MB for main workspace.
829711 variants loaded from .bim file.
30 people (0 males, 0 females, 30 ambiguous) loaded from .fam.
Ambiguous sex IDs written to subsample_maf.nosex .
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 30 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is exactly 1.
4507 variants removed due to minor allele threshold(s)
(--maf/--max-maf/--mac/--max-mac).
825204 variants and 30 people pass filters and QC.
Note: No phenotypes present.
--make-bed to subsample_maf.bed + subsample_maf.bim + subsample_maf.fam ...
done.

```

**Comment by Rosemeis** [comment]
It should be fixed in v1.36.2. Sorry for the inconvenience, and thank you again for reporting!
