### ISSUE TITLE
ModuleNotFoundError: No module named 'pcangsd.pcangsd'; 'pcangsd' is not a package

### ISSUE THREAD

**Issue by IgnasiLucas** [Rosemeis/pcangsd#92]
After installing successfully, when I run pcangsd I get the following error:

`Traceback (most recent call last):
  File "/home/joiglu/.conda/envs/bio/bin/pcangsd", line 5, in <module>
    from pcangsd.pcangsd import main
ModuleNotFoundError: No module named 'pcangsd.pcangsd'; 'pcangsd' is not a package`

I think this is related to the naming of the pcangsd.py file inside pcangsd folder, as described in the link below:

[https://stackoverflow.com/questions/54333865/python-no-module-named-error-package-is-not-a-package](https://stackoverflow.com/questions/54333865/python-no-module-named-error-package-is-not-a-package)

**Comment by Rosemeis** [comment]
Can you write the command that prompted the error? :-)

/Jonas

**Comment by IgnasiLucas** [comment]
Yes, the error appeared as soon as I run pcangsd, like:

`pcangsd -h`

I also noticed that the `pcangsd` executable is a text file containing this:

> #!/home/joiglu/.conda/envs/bio/bin/python3.12
> #-*- coding: utf-8 -*-
> import re
> import sys
> from pcangsd.pcangsd import main
> if __name__ == '__main__':
>     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
>     sys.exit(main())`

And if I edit it and substitute `from pcangsd.pcangsd import main` for `from pcangsd import main`, then, the command `pcangsd -h` does show the help without error, but it becomes unable to import "admixture" when I run `pcangsd --beagle input.beagle.gz`. The error that shows then is this:

> `-------------------------------------`
> PCAngsd v1.35
> Jonas Meisner and Anders Albrechtsen.
> Using 1 thread(s).
> `-------------------------------------`
> 
> Traceback (most recent call last):
>   File "/home/joiglu/.conda/envs/bio/bin/pcangsd", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/joiglu/software/PCANGSD/pcangsd/pcangsd.py", line 145, in main
>     from pcangsd import admixture
> ImportError: cannot import name 'admixture' from 'pcangsd' (/home/joiglu/software/PCANGSD/pcangsd/pcangsd.py)

It's not that I expect to fix the problem by editing the executable, but I was trying to understand the problem. Thanks for your help.

**Comment by johannabeam** [comment]
Hi, I am having a similar problem and cannot get pcangsd to run. 
I am using the following code: 
```
python /path/to/pcangsd/pcangsd/pcangsd.py -b GL_YBCH_hz.beagle.gz -e 4 -t 10 -o pcangsd_YBCH_hz
```
And keep getting errors such as the following:

```
Traceback (most recent call last):
  File "/path/to/pcangsd/pcangsd/pcangsd.py", line 552, in <module>
    main()
  File "/path/to/pcangsd/pcangsd/pcangsd.py", line 145, in main
    from pcangsd import admixture
ImportError: cannot import name 'admixture' from 'pcangsd' (/path/to/pcangsd/pcangsd/pcangsd.py)
```
I have confirmed that admixture.py is in that `/pcangsd/pcangsd/` directory. 
Any insight you have would be greatly appreciated. Thanks!

**Comment by Rosemeis** [comment]
Hi Johanna,

If you have installed pcangsd as described on the GitHub, it is only available as a command-line program `pcangsd`. There are some older tutorials which show `python /path/to/pcangsd/pcangsd/pcangsd.py`, but you need to simply just use `pcangsd -b GL_YBCH_hz.beagle.gz -e 4 -t 10 -o pcangsd_YBCH_hz`. Sorry! :-)

Let me know if it helped!

Best,
Jonas

**Comment by johannabeam** [comment]
Gosh, I just forgot a line of the install code! Thanks for letting me know; it's running fine now!
